@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashNotesParser" as FlashNotesParser LOGIC_COLOR
participant ":DeleteDeckCommandParser" as DeleteDeckCommandParser LOGIC_COLOR
participant "d:DeleteDeckCommand" as DeleteDeckCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteDeck nameOfDeck")
activate LogicManager

LogicManager -> FlashNotesParser : parseCommand("deleteDeck nameOfDeck")
activate FlashNotesParser

create DeleteDeckCommandParser
FlashNotesParser -> DeleteDeckCommandParser
activate DeleteDeckCommandParser

DeleteDeckCommandParser --> FlashNotesParser
deactivate DeleteDeckCommandParser

FlashNotesParser -> DeleteDeckCommandParser : parse("nameOfDeck")
activate DeleteDeckCommandParser

create DeleteDeckCommand
DeleteDeckCommandParser -> DeleteDeckCommand
activate DeleteDeckCommand

DeleteDeckCommand --> DeleteDeckCommandParser : d
deactivate DeleteDeckCommand

DeleteDeckCommandParser --> FlashNotesParser : d
deactivate DeleteDeckCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteDeckCommandParser -[hidden]-> FlashNotesParser
destroy DeleteDeckCommandParser

FlashNotesParser --> LogicManager : d
deactivate FlashNotesParser

LogicManager -> DeleteDeckCommand : execute()
activate DeleteDeckCommand

DeleteDeckCommand -> Model : deleteDeck("nameOfDeck")
activate Model

Model --> DeleteDeckCommand
deactivate Model

create CommandResult
DeleteDeckCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteDeckCommand
deactivate CommandResult

DeleteDeckCommand --> LogicManager : result
deactivate DeleteDeckCommand

[<--LogicManager
deactivate LogicManager
@enduml
