@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFlashNotes <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class FlashNotes
Class ReadOnlyFlashNotes
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Flashcard {
Class Flashcard
Class Question
Class Answer
Class UniqueFlashcardList
}

Package Tag {
Class Tag
}

Package Deck {
Class Deck
Class UniqueDeckList
}
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FlashNotes .up.|> ReadOnlyFlashNotes

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" FlashNotes
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FlashNotes *--> "1" UniqueFlashcardList
UniqueFlashcardList o--> "*" Flashcard
Flashcard *--> Question
Flashcard *--> Answer
Flashcard *--> Tag
FlashNotes *--> "1" UniqueDeckList
UniqueDeckList o--> "*" Deck

Deck -right[hidden]- Flashcard
@enduml
