@startuml
!include style.puml

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : "review"
activate ui UI_COLOR

ui -[USER_COLOR]> ui : executeCommand("review")
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("review")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> logic : execute(model)
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> model : setUpReviewList()
activate model MODEL_COLOR

model -[MODEL_COLOR]-> logic
deactivate model

logic -[LOGIC_COLOR]-> ui
deactivate logic

ui--[UI_COLOR]> user
deactivate ui

@enduml
