@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
interface RootNode <<Interface>>
Class XYZListRoot
Class HelpWindow
Class ResultDisplay
Class XYZListPanel
Class XYZCard
Class StatusBarFooter
Class CommandBox
Class ReviewWindow
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow  -- "1" RootNode
RootNode --> XYZListRoot
XYZListRoot *-down-> ReviewWindow
XYZListRoot *-down-> HelpWindow
XYZListRoot *-down-> CommandBox
XYZListRoot *-down-> ResultDisplay
XYZListRoot *-down-> XYZListPanel
XYZListRoot *-down-> StatusBarFooter

XYZListPanel -down-> "*" XYZCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
XYZListPanel --|> UiPart
XYZCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
ReviewWindow --|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
HelpWindow -[hidden]right-> ReviewWindow
MainWindow -left-> Logic

XYZListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
